name: Build Antora Documentation

on:
  push:
    branches:
      - anotra  # or the branch where Antora docs are maintained

jobs:
  build-antora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'antora' branch
        uses: actions/checkout@v4
        with:
          ref: anotra
          fetch-depth: 1  # (optional) default, fetches only latest commit

      # Step 2: Setup Node.js (required for Antora)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install Antora CLI and site generator
      - name: Install Antora
        run: |
          npm install -g @antora/cli @antora/site-generator-default

      - name: List files in the current directory
        run: |
          ls -la

      - name: PWD
        run: pwd

      # Step 4: Build the Antora site
      - name: Build Antora site
        run: |
           antora --generator @antora/site-generator-default antora-playbook.yml

      # - name: Run setup.sh script
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     chmod +x .github/workflows/setup.sh
      #     .github/workflows/setup.sh

      - name: Run the deploy sc
        run: |
          cd build-output
          echo "Current directory: $(pwd)"
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          git remote add origin https://${ secrets.GITHUB_TOKEN }@github.com/${ github.repository }.git

          #adding .nojekyll to prevent Jekyll processing i.e. github should not ignore "_" folder
          echo "Adding .nojekyll to prevent Jekyll"
          touch .nojekyll
          git add .
          echo "Files to be committed:"
          git commit -m "Deploy Antora site"

          #Modify the branch name to 'deploy'
          git branch -M deploy

          echo "Pushing to remote repository..."
          git push -f origin deploy


      - name: Echo message
        run: echo "Antora documentation build completed successfully."
